const CREATE = "CREATE";
const FETCH_ALL = "FETCH_ALL";
const FETCH_BY_SEARCH = "FETCH_BY_SEARCH";
const FETCH_POST = "FETCH_POST";
const UPDATE = "UPDATE";
const DELETE = "DELETE";
const LIKE = "LIKE";
const COMMENT = "COMMENT";
const FETCH_BY_CREATOR = "FETCH_BY_CREATOR";

const START_LOADING = "START_LOADING";
const END_LOADING = "END_LOADING";

const AUTH = "AUTH";
const LOGOUT = "LOGOUT";

export {
  AUTH,
  LOGOUT,
  CREATE,
  FETCH_ALL,
  FETCH_BY_SEARCH,
  FETCH_POST,
  UPDATE,
  DELETE,
  LIKE,
  COMMENT,
  FETCH_BY_CREATOR,
  START_LOADING,
  END_LOADING,
};
